#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3309/chat_app_db
#spring.datasource.username=hoangdeptrai
#spring.datasource.password=123456
##allow table's name like tblProduct
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.properties.hibernate.format_sql=true

#  spring:
#    datasource:
#      url: jdbc:mysql://localhost:3306/chat_app_db
#      username: hoangvo
#      password: 123456
#      driver-class-name: com.mysql.jdbc.Driver
#    jpa:
#      hibernate:
#        ddl-auto: update
#        naming:
#          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      properties:
#        hibernate:
#          format_sql: true
# ?createDatabaseIfNotExist=true
server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/chat_app-database?createDatabaseIfNotExist=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs.path: /api-docs

social:
  firebase:
    bucketName: chatapp-9b773.appspot.com
    serviceAccount: file:service-account-key.json
#com.google.cloud.storage.StorageException: Invalid bucket name: 'https://storage.googleapis.com/chatapp-9b773.appspot.com/%s'